{
    "openapi": "3.0.1",
    "info": {
        "title": "Tickets",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "When a customer contacts your support team to request help with an issue, create a ticket to track that request and keep a record of it for future reference.",
        "x-hubspot-related-documentation": [
            {
                "name": "Tickets Guide",
                "url": "https://developers.hubspot.com/beta-docs/guides/api/crm/objects/tickets"
            }
        ],
        "x-hubspot-introduction": "Use the tickets API to create and manage CRM records that represent customer service requests in your CRM."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/tickets"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Merge"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read tickets by ID or property",
                "operationId": "post-/crm/v3/objects/tickets/batch/read_read",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ],
                "description": "Returns a batch of tickets retrieved by internal ID or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/{ticketId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a ticket by ID",
                "description": "Read an Object identified by `{ticketId}`. `{ticketId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/tickets/{ticketId}_getById",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a ticket by ID",
                "description": "Move an Object identified by `{ticketId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/tickets/{ticketId}_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update a ticket by ID",
                "description": "Perform a partial update of an Object identified by `{ticketId}`or optionally a unique property value as specified by the `idProperty` query param. `{ticketId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string[...]",
                "operationId": "patch-/crm/v3/objects/tickets/{ticketId}_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ]
            }
        },
        "/merge": {
            "post": {
                "tags": [
                    "Merge"
                ],
                "summary": "Merge two tickets with same type",
                "operationId": "post-/crm/v3/objects/tickets/merge_merge",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ],
                "description": "Returns the merged ticket object resulting from combining two tickets of the same type."
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of tickets by ID",
                "operationId": "post-/crm/v3/objects/tickets/batch/archive_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ],
                "description": "Archives a batch of tickets by ID. Returns no content on success (204)."
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of tickets",
                "operationId": "post-/crm/v3/objects/tickets/batch/create_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ],
                "description": "Returns the created batch of ticket objects, with partial success indicated by a 207 response."
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update tickets by ID or property",
                "operationId": "post-/crm/v3/objects/tickets/batch/update_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ],
                "description": "Returns the updated batch of ticket objects identified by internal ID or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "List a page of tickets",
                "description": "Read a page of tickets. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/tickets_getPage",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a new ticket",
                "description": "Create a ticket with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard tickets is provided.",
                "operationId": "post-/crm/v3/objects/tickets_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert tickets by property",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/tickets/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "operationId": "post-/crm/v3/objects/tickets/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ],
                "description": "Returns a list of tickets matching the specified search criteria and filters.",
                "summary": "Search for tickets"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}